# Generated by Django 3.1.7 on 2021-03-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_auto_20210302_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='type',
            new_name='route_type',
        ),
    ]
