# Generated by Django 3.1.7 on 2021-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_auto_20210319_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='gpx_track',
            field=models.FileField(blank=True, upload_to='static/tracks', verbose_name='Трек маршрута в формате GPX'),
        ),
    ]
