# Generated by Django 3.1.7 on 2021-03-26 10:15

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_route_gpx_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='long_desc',
            field=djrichtextfield.models.RichTextField(verbose_name='Полное описание'),
        ),
    ]
