# Generated by Django 3.1.7 on 2021-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_auto_20210326_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='complexity',
            field=models.IntegerField(choices=[(1, 'Простой'), (2, 'Обычный'), (3, 'Продвинутый'), (4, 'Сложный'), (5, 'Экстремальный')], db_index=True, default=1, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.IntegerField(choices=[(1, 'Пеший'), (2, 'Велосипедный'), (3, 'Водный'), (4, 'Автомобильный'), (5, 'Лыжный'), (6, 'Горный')], db_index=True, default=1, verbose_name='Тип'),
        ),
    ]
