# Generated by Django 3.1.7 on 2021-03-27 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0027_auto_20210326_2014'),
        ('travelapp', '0009_auto_20210326_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='authapp.instructor', verbose_name='Гид'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='travelapp.route', verbose_name='Маршрут'),
        ),
    ]
