# Generated by Django 3.1.7 on 2021-04-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_auto_20210327_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='ya_constructor',
            field=models.URLField(null=True, verbose_name='Маршрут Yandex Map'),
        ),
    ]
