# Generated by Django 3.1.7 on 2021-03-19 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_auto_20210304_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='routes_run',
            new_name='trips_run',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='activation_key_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 14, 24, 51, 878866, tzinfo=utc), verbose_name='Крайний срок текущей активации'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 14, 24, 51, 878866, tzinfo=utc), verbose_name='Дата рождения'),
        ),
    ]
