# Generated by Django 3.1.7 on 2021-03-23 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_auto_20210319_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='activation_key_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 15, 54, 38, 755872, tzinfo=utc), verbose_name='Крайний срок текущей активации'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 15, 54, 38, 755872, tzinfo=utc), verbose_name='Дата рождения'),
        ),
    ]
