# Generated by Django 3.1.7 on 2021-03-23 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_auto_20210323_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='activation_key_expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 16, 3, 36, 275721, tzinfo=utc), verbose_name='Крайний срок текущей активации'),
        ),
    ]
