# Generated by Django 3.1.7 on 2021-03-26 17:14

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_auto_20210323_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[authapp.models.email_is_lowercase], verbose_name='Адрес Email'),
        ),
    ]
