# Generated by Django 3.1.7 on 2021-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0027_auto_20210326_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='about',
            field=models.TextField(blank=True, default='Обо мне', verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='home_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место проживания'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='about',
            field=models.TextField(blank=True, default='Обо мне', verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='home_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место проживания'),
        ),
    ]
