# Generated by Django 3.1.7 on 2021-04-18 12:53

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0029_auto_20210402_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static/user_pics'),
        ),
    ]
