# Generated by Django 3.1.7 on 2021-04-19 10:26

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0030_auto_20210418_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='user_pics'),
        ),
    ]
