# Generated by Django 3.1.7 on 2021-04-20 12:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0031_auto_20210419_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/user_pics'),
        ),
    ]
