# Generated by Django 3.1.7 on 2021-03-19 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_auto_20210304_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_edit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время изменения'),
            preserve_default=False,
        ),
    ]
