# Generated by Django 3.1.7 on 2021-04-18 12:53

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_comment_last_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentphoto',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='static/comment_media'),
        ),
    ]
