# Generated by Django 3.1.7 on 2021-04-19 10:26

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_auto_20210418_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentphoto',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='comment_media'),
        ),
    ]
