# Generated by Django 3.1.7 on 2021-04-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_auto_20210419_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcomment',
            name='instructor_score',
            field=models.IntegerField(choices=[(1, 'Понравился'), (2, 'Не понравился')], null=True, verbose_name='Оценка инструктора'),
        ),
    ]
